services:
  - type: web
    name: puzzlebox-api
    env: dotnet
    plan: free
    region: ohio
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/puzzleBox.dll --urls http://0.0.0.0:$PORT"
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production